description: 'Check if release exists'
branding:
  icon: 'arrow-right-circle'
  color: 'gray-dark'

inputs:
  token:
    description: 'github token'
    required: true
  release:
    description: 'release name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: check runner
      if: ${{ runner.os != 'Linux' }}
      shell: bash
      run: |
        echo "::error title=wrong runner os error hint::only Linux is supported"
        exit 1
    - name: check release
      shell: bash
      run: |
        RES=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/releases 2>/dev/null)
        RES=$(echo $RES | jq '.[] | select(.name == ${{ inputs.release }})')
        if [ -z "$RES" ]; then
          echo 'release_exists=false' >> $GITHUB_ENV
          echo 'release ${{ inputs.release }} is available' >> $GITHUB_STEP_SUMMARY
        else
          echo 'release_exists=true' >> $GITHUB_ENV
          echo 'release ${{ inputs.release }} exists' >> $GITHUB_STEP_SUMMARY
        fi
